# Generated by Django 5.1.15 on 2026-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0016_alter_thirdpartymodelversion_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinterface',
            name='skill_name',
            field=models.CharField(choices=[('TextClassification', 'TextClassification'), ('NamedEntityRecognition', 'NamedEntityRecognition'), ('ObjectDetection', 'ObjectDetection'), ('InstanceSegmentation', 'InstanceSegmentation')], max_length=255, null=True),
        ),
    ]
