# -*- coding: utf-8 -*-
"""标注编辑器（editor）用户可见文案词库。"""

DICT = {
    "Buffering Media Source": "正在缓冲媒体源",
    "TextArea Input": "文本区域输入",
    "Playback speed": "播放速度",
    "Image Tag": "图像标签",
    "Unset this result as a ground truth": "取消将此结果设为基准答案",
    "Compare all annotations": "比较所有标注",
    "Annotators and Reviewers will not be able to skip this task": "标注员和审核员将无法跳过此任务",
    "Save results: [ Ctrl+Enter ]": "保存结果：[ Ctrl+Enter ]",
    "Unlock Region": "解锁区域",
    "Not implemented": "未实现",
    "Start frame": "起始帧",
    "End frame": "结束帧",
    "Label whole utterance": "标注整个话语",
    "Delete Region": "删除区域",
    "Number of Mel bands must be positive.": "Mel 频带数量必须为正数。",
    "An audio loading error occurred": "音频加载出错",
    "Audio zoom y-axis": "音频 Y 轴缩放",
    "Loop Regions": "循环区域",
    "Auto-play New Regions": "自动播放新区域",
    "Spectrogram progress overlay": "频谱图进度覆盖层",
    "Keep label selected after creating a region": "创建区域后保持标签选中",
    "not submitted draft": "未提交的草稿",
    "switch to current draft": "切换到当前草稿",
    "Unset ground truth": "取消基准答案",
    "Set this result as a ground truth": "将此结果设为基准答案",
    "Delete selected annotation": "删除所选标注",
    "Create new annotation": "创建新标注",
    "Carousel left": "轮播左移",
    "Carousel right": "轮播右移",
    "Previous task": "上一个任务",
    "Move left": "左移",
    "Move right": "右移",
    "Accept annotation: [ Ctrl+Enter ]": "接受标注：[ Ctrl+Enter ]",
    "Fix + Accept": "修复并接受",
    "Reject annotation: [ Ctrl+Space ]": "拒绝标注：[ Ctrl+Space ]",
    "Cancel skip: []": "取消跳过：[ ]",
    "Empty annotations denied in this project": "此项目不允许空标注",
    "Submit current annotation": "提交当前标注",
    "Add a comment": "添加评论",
    "Cancel (skip) task: [ Ctrl+Space ]": "取消（跳过）任务：[ Ctrl+Space ]",
    "Update this task: [ Alt+Enter ]": "更新此任务：[ Alt+Enter ]",
    "Click to add...": "点击添加…",
    "Segmentation Tools": "分割工具",
    "Delete annotation": "删除标注",
    "Delete selected region": "删除所选区域",
    "No label": "无标签",
    "Delete Relation": "删除关系",
    "Show all": "显示全部",
    "Hide all": "隐藏全部",
    "Order by oldest": "按最早排序",
    "Order by newest": "按最新排序",
    "Show all regions": "显示所有区域",
    "Hide all regions": "隐藏所有区域",
    "Link to...": "关联到…",
    "Serialize all": "序列化全部",
    "Serialize current": "序列化当前",
    "Load task": "加载任务",
    "Global Hotkeys": "全局快捷键",
    "Error during submit": "提交时出错",
    "Error during skip, try again": "跳过时出错，请重试",
    "Error during cancel skipping task, try again": "取消跳过的任务时出错，请重试",
    "Error during accept, try again": "接受时出错，请重试",
    "Error during reject, try again": "拒绝时出错，请重试",
    "Select a region": "选择一个区域",
    "Ellipse region": "椭圆区域",
    "Key Point": "关键点",
    "Magic Wand": "魔棒",
    "The Magic Wand is not supported on rotated images": "旋转图像不支持魔棒工具",
    "The Magic Wand is not supported if the crosshair is turned on": "开启十字准线时不支持魔棒工具",
    "Polygon region": "多边形区域",
    "3 Point Rectangle": "三点矩形",
    "Rotate Left": "向左旋转",
    "Rotate Right": "向右旋转",
    "Vector region": "向量区域",
    "Video vector region": "视频向量区域",
    "Pan Image": "平移图像",
    "Zoom In": "放大",
    "Zoom to fit": "适应窗口",
    "Zoom to actual size": "实际大小",
    "Zoom Out": "缩小",
    "just now": "刚刚",
    "1 minute ago": "1 分钟前",
    "1 hour ago": "1 小时前",
    "No more annotations": "没有更多标注",
    "You're all caught up!": "全部处理完毕！",
    "You don't have access to this task": "你没有访问此任务的权限",
    "Time Series Segmentation": "时间序列分割",
    "Quick Filter": "快速筛选",
    "Audio Segmentation": "音频分割",
    "No label selected. Annotation will not be created.": "未选择标签，不会创建标注。",
    "Restore broken position": "恢复损坏的位置",
    "Can't find the text": "找不到文本",
    "Select a label first to enable labeling": "请先选择标签以启用标注",
    "Label whole utterance (disabled)": "标注整个话语（已禁用）",
    "Automatically sync transcript scrolling with audio playback": "自动将转写滚动与音频播放同步",
    "unknown action": "未知操作",
    "Play an audio": "播放音频",
    "Unsaved Annotation": "未保存的标注",
    "No annotations submitted yet": "尚未提交标注",
    "This will": "这将",
    "delete all existing regions": "删除所有现有区域",
    "This action cannot be undone.": "此操作无法撤销。",
    "Compare All": "比较全部",
    "Go to Previous Task": "上一个任务",
    "Summary": "摘要",
    "Side-by-side": "并排",
    "Loading comments...": "正在加载评论…",
    "See a log of user actions for this annotation": "查看此标注的用户操作日志",
    "Selected Message": "选中的消息",
    "Downloading image": "正在下载图像",
    "Redo": "重做",
    "Reset Prelabeling": "重置预标注",
    "Hide Instructions": "隐藏说明",
    "Move sidepanel to the bottom": "将侧面板移到底部",
    "Display Labels by default in Results panel": "默认在结果面板中显示标签",
    "Show Annotations panel": "显示标注面板",
    "Show Predictions panel": "显示预测面板",
    "No ratings": "没有评分",
    "No data": "没有数据",
    "Failed to load": "加载失败",
    "Task Summary": "任务摘要",
    "Task Data": "任务数据",
    "Add Inside": "添加为子项",
    "Create Annotation": "创建标注",
    "Reject": "拒绝",
    "FFT Samples": "FFT 采样数",
    "Spectogram dB": "频谱图 dB",
    "Windowing Function": "窗口函数",
    "Link regions to define relationships between them": "关联区域以定义它们之间的关系",
    "Comments": "评论",
    "Rating:": "评分：",
    "Text:": "文本：",
    "Choices:": "选项：",
    "Taxonomy:": "分类：",
    "Start labeling and track your results": "开始标注并跟踪你的结果",
    "using this panel": "使用此面板",
    "All regions hidden": "所有区域已隐藏",
    "Adjust or remove the filters to view": "调整或移除筛选条件以查看",
    "Adjust or remove filters to view": "调整或移除筛选条件以查看",
    "Group Manually": "手动分组",
    "Group by Label": "按标签分组",
    "Group by Tool": "按工具分组",
    "Order by Time": "按时间排序",
    "Order by Score": "按得分排序",
    "Order by Media Start Time": "按媒体开始时间排序",
    "Linear": "线性",
    "Logarithmic": "对数",
    "Mel Bands": "Mel 频带",
    "FFT Size": "FFT 大小",
    "Window Function": "窗口函数",
    "Rectangular": "矩形",
    "Min dB": "最小 dB",
    "Max dB": "最大 dB",
    "Loading file...": "正在加载文件…",
    "Press Shift + Enter to Add": "按 Shift + Enter 添加",
    "Zoom To Fit": "适应窗口",
    "Zoom 100%": "缩放 100%",
    "Note:": "注意：",
    "Also check that:": "还要检查：",
    "Network is reachable": "网络可访问",
    "Things to look out for:": "需要注意的事项：",
    "Read more on that here.": "在此处了解更多。",
    "Technical description:": "技术说明：",
    "No URL provided for download": "未提供下载 URL",
    "Network error": "网络错误",
    "Dimensions have not been set.": "尚未设置尺寸。",
    "New content is available and will be used when all ": "新内容可用，将在所有",
    "tabs for this page are closed. See http://bit.ly/CRA-PWA.": "此页面的标签页都关闭后使用。参见 http://bit.ly/CRA-PWA。",
    "Content is cached for offline use.": "内容已缓存，可离线使用。",
    "Error during service worker registration:": "注册 Service Worker 时出错：",
    "No internet connection found. App is running in offline mode.": "未检测到网络连接，应用正以离线模式运行。",
    "This web app is being served cache-first by a service ": "此 Web 应用由 Service Worker 以缓存优先方式提供，",
    "worker. To learn more, visit http://bit.ly/CRA-PWA": "了解更多请访问 http://bit.ly/CRA-PWA",
    "Error seeking video:": "视频定位出错：",
    "No video control is found": "未找到视频控件",
    "No video vector control is found": "未找到视频向量控件",
    "No video timeline control is found": "未找到视频时间轴控件",
    "Error while loading audio. Check": "音频加载出错，请检查",
    "field in task.": "任务中的字段。",
    "Error occurred while loading the data": "加载数据时出错",
    "Labeling hotkeys": "标注快捷键",
    "Enables quick selection of labels using hotkeys": "启用后可使用快捷键快速选择标签",
    "Enable labeling hotkeys": "启用标注快捷键",
    "Show hotkeys on tooltips": "在提示中显示快捷键",
    "Displays keybindings on tools and actions tooltips": "在工具和操作的提示中显示快捷键",
    "Show hotkey tooltips": "显示快捷键提示",
    "Show hotkeys on labels": "在标签上显示快捷键",
    "Displays keybindings on labels": "在标签上显示快捷键",
    "Show labels hotkey tooltips": "显示标签快捷键提示",
    "Show region labels": "显示区域标签",
    "Display region label names": "显示区域标签名称",
    "Show labels inside the regions": "在区域内显示标签",
    "Allows continuous region creation using the selected label": "允许使用所选标签连续创建区域",
    "Select region after creating it": "创建区域后选中它",
    "Automatically selects newly created regions": "自动选中新建的区域",
    "Select regions after creating": "创建后选中区域",
    "Text Tag": "文本标签",
    "Show line numbers": "显示行号",
    "Identify and reference specific lines of text in your document": "识别并引用文档中的特定文本行",
    "Show line numbers for Text": "为文本显示行号",
    "Keep selected tool": "保持所选工具",
    "Persists the selected tool across tasks": "在任务之间保留所选工具",
    "Remember Selected Tool": "记住所选工具",
    "Pixel smoothing on zoom": "缩放时像素平滑",
    "Smooth image pixels when zoomed in": "放大时平滑图像像素",
    "Enable image smoothing when zoom": "缩放时启用图像平滑",
    "Invert zoom direction": "反转缩放方向",
    "Invert the direction of scroll-to-zoom": "反转滚动缩放的缩放方向",
    "Enable inverted zoom direction": "启用反转缩放方向",
    "Allow drawing outside of video boundaries": "允许在视频边界外绘制",
    "Video hop size": "视频步进大小",
    "switch to submitted result": "切换到已提交的结果",
    "Set ground truth": "设为基准答案",
    "Skipped annotation": "已跳过的标注",
    "Toggle visibility of current annotation": "切换当前标注的可见性",
    "View all annotations": "查看所有标注",
    "Toggle view of all annotations": "切换所有标注的显示",
    "Unresolved Comments": "未解决的评论",
    "All Comments Resolved": "所有评论已解决",
    "Annotation ID": "标注 ID",
    "Prediction Score": "预测得分",
    "Last Updated": "最近更新",
    "Ground Truth": "基准答案",
    "Annotation link copied to clipboard": "标注链接已复制到剪贴板",
    "Annotation ID copied to clipboard": "标注 ID 已复制到剪贴板",
    "Delete annotation?": "删除标注？",
    "Copy Annotation ID": "复制标注 ID",
    "Duplicate Annotation": "复制标注",
    "Copy Annotation Link": "复制标注链接",
    "Open Performance Dashboard": "打开性能看板",
    "Show Other Annotations": "显示其他标注",
    "Delete Annotation": "删除标注",
    "Auto-Accept Suggestions": "自动接受建议",
    "Your annotation has been submitted.": "你的标注已提交。",
    "You've viewed all annotations for this task.": "你已查看此任务的全部标注。",
    "All tasks in the queue have been completed": "队列中的全部任务都已完成",
    "Review Instructions": "查看说明",
    "Loading annotation...": "正在加载标注…",
    "Waiting to load...": "等待加载…",
    "Open Annotation Tab": "打开标注标签页",
    "Show instructions": "显示说明",
    "Cancel (skip) task [ Ctrl+Space ]": "取消（跳过）任务 [ Ctrl+Space ]",
    "Complete all regions before submitting": "提交前请完成所有区域",
    "Complete all regions before updating": "更新前请完成所有区域",
    "Complete all regions before accepting": "接受前请完成所有区域",
    "Submit annotation": "提交标注",
    "No changes were made": "没有做出更改",
    "Delete comment": "删除评论",
    "Cancel delete": "取消删除",
    "Cancel edit": "取消编辑",
    "Comment options": "评论选项",
    "Select an object to link it to this comment.": "选择一个目标将其关联到此评论。",
    "Unlink comment": "取消关联评论",
    "less than a minute ago": "不到一分钟前",
    "seconds ago": "秒前",
    "Grouped by Label": "已按标签分组",
    "By Tool": "按工具",
    "Grouped by Tool": "已按工具分组",
    "By Time": "按时间",
    "By Score": "按得分",
    "By Media Start Time": "按媒体开始时间",
    "Expand Bottom Panel": "展开底部面板",
    "Collapse Bottom Panel": "收起底部面板",
    "Spectrogram Settings": "频谱图设置",
    "Scale": "缩放",
    "Color Scheme": "配色方案",
    "Playback Settings": "播放设置",
    "audio wave": "音频波形",
    "timeline": "时间轴",
    "Read Documentation": "阅读文档",
    "There was an issue loading URL from": "从以下位置加载 URL 时出现问题",
    "URL:": "URL：",
    "URL is valid": "URL 有效",
    "Show all authors": "显示所有作者",
    "Avg:": "平均：",
    "Distribution": "分布",
    "more": "更多",
    "annotations": "标注",
    "Selected Message": "选中的消息",
    "Transform error:": "变换出错：",
    "Drag move error:": "拖动移动出错：",
    "Drag end error:": "拖动结束出错：",
    "Transform end error:": "变换结束出错：",
}

TEXT = {
    "Yes": "是",
    "Summary": "摘要",
    "Side-by-side": "并排",
    "Comments": "评论",
    "Zoom In": "放大",
    "Zoom Out": "缩小",
    "Zoom To Fit": "适应窗口",
    "Zoom 100%": "缩放 100%",
    "Redo": "重做",
    "Reject": "拒绝",
    "Compare All": "比较全部",
    "No ratings": "没有评分",
    "No data": "没有数据",
    "Failed to load": "加载失败",
    "Task Summary": "任务摘要",
    "Task Data": "任务数据",
    "Add Inside": "添加为子项",
    "Create Annotation": "创建标注",
    "Show all": "显示全部",
    "Hide all": "隐藏全部",
    "Order by oldest": "按最早排序",
    "Order by newest": "按最新排序",
    "Show all regions": "显示所有区域",
    "Hide all regions": "隐藏所有区域",
    "Link to...": "关联到…",
    "Loading comments...": "正在加载评论…",
    "Rating:": "评分：",
    "Text:": "文本：",
    "Choices:": "选项：",
    "Taxonomy:": "分类：",
    "No label": "无标签",
    "Delete Region": "删除区域",
    "Delete Relation": "删除关系",
    "Start labeling and track your results": "开始标注并跟踪你的结果",
    "using this panel": "使用此面板",
    "All regions hidden": "所有区域已隐藏",
    "Adjust or remove the filters to view": "调整或移除筛选条件以查看",
    "Group Manually": "手动分组",
    "Group by Label": "按标签分组",
    "Group by Tool": "按工具分组",
    "Order by Time": "按时间排序",
    "Order by Score": "按得分排序",
    "Order by Media Start Time": "按媒体开始时间排序",
    "FFT Samples": "FFT 采样数",
    "Spectogram dB": "频谱图 dB",
    "Windowing Function": "窗口函数",
    "Mel Bands": "Mel 频带",
    "FFT Size": "FFT 大小",
    "Window Function": "窗口函数",
    "Min dB": "最小 dB",
    "Max dB": "最大 dB",
    "Loading file...": "正在加载文件…",
    "Press Shift + Enter to Add": "按 Shift + Enter 添加",
    "Linear": "线性",
    "Logarithmic": "对数",
    "Mel": "Mel",
    "Hann": "Hann",
    "Hamming": "Hamming",
    "Blackman": "Blackman",
    "Rectangular": "矩形",
    "Inferno": "Inferno",
    "Magma": "Magma",
    "Viridis": "Viridis",
    "Plasma": "Plasma",
    "Previous task": "上一个任务",
    "Go to Previous Task": "上一个任务",
    "Playback speed": "播放速度",
    "Start frame": "起始帧",
    "End frame": "结束帧",
    "Loop Regions": "循环区域",
    "Auto-play New Regions": "自动播放新区域",
    "Audio zoom y-axis": "音频 Y 轴缩放",
    "Buffering Media Source": "正在缓冲媒体源",
    "Time Series Segmentation": "时间序列分割",
    "Audio Segmentation": "音频分割",
    "Quick Filter": "快速筛选",
    "Select a region": "选择一个区域",
    "Unsaved Annotation": "未保存的标注",
    "No annotations submitted yet": "尚未提交标注",
    "This will": "这将",
    "delete all existing regions": "删除所有现有区域",
    "This action cannot be undone.": "此操作无法撤销。",
    "No more annotations": "没有更多标注",
    "You're all caught up!": "全部处理完毕！",
    "You don't have access to this task": "你没有访问此任务的权限",
    "Add a comment": "添加评论",
    "Compare all annotations": "比较所有标注",
    "Compare All Annotations": "比较所有标注",
    "Skip": "跳过",
    "Cancel skip": "取消跳过",
    "Was skipped": "已跳过",
    "Submit": "提交",
    "Spectrogram Settings": "频谱图设置",
    "Scale": "缩放",
    "Color Scheme": "配色方案",
    "Playback Settings": "播放设置",
    "audio wave": "音频波形",
    "timeline": "时间轴",
    "Read Documentation": "阅读文档",
    "Show all authors": "显示所有作者",
    "Avg:": "平均：",
    "Distribution": "分布",
    "more": "更多",
    "Annotation History": "标注历史",
    "Expand Bottom Panel": "展开底部面板",
    "Collapse Bottom Panel": "收起底部面板",
    "Link regions to define relationships between them": "关联区域以定义它们之间的关系",
    "Adjust or remove filters to view": "调整或移除筛选条件以查看",
    "There was an issue loading URL from": "从以下位置加载 URL 时出现问题",
    "URL:": "URL：",
    "URL is valid": "URL 有效",
    "Downloading image": "正在下载图像",
    "See a log of user actions for this annotation": "查看此标注的用户操作日志",
    "Selected Message": "选中的消息",
    "Review Instructions": "查看说明",
    "Show instructions": "显示说明",
}
