# -*- coding: utf-8 -*-
"""主界面英文 -> 简体中文 词库（apps/labelstudio）。"""

# 引号字符串翻译表
DICT = {
    "Learn more": "了解更多",
    "Did you know?": "你知道吗？",
    "Copied!": "已复制！",
    "Bucket prefix": "存储桶前缀",
    "Create new project": "创建新项目",
    "Reset Cache": "重置缓存",
    "Drop All Tabs": "关闭所有标签页",
    "Delete Project": "删除项目",
    "This action cannot be undone. Are you sure?": "此操作无法撤销，确定继续吗？",
    "Add Source Storage": "添加源存储",
    "Amazon S3": "Amazon S3",
    "Google Cloud Storage": "Google Cloud Storage",
    "Azure Blob Storage": "Azure Blob Storage",
    "Redis Storage": "Redis 存储",
    "Use pre-signed URLs (On) / Proxy through the platform (Off)": "使用预签名 URL（开）/ 通过平台代理（关）",
    "When pre-signed URLs are enabled, all data bypasses the platform and user browsers directly read data from storage": "启用预签名 URL 后，所有数据将绕过平台，由用户浏览器直接从存储中读取",
    "Expire pre-signed URLs (minutes)": "预签名 URL 有效期（分钟）",
    "Connection refused": "连接被拒绝",
    "Server not responding. Is it still running?": "服务器无响应，它还在运行吗？",
    "Select an option": "请选择选项",
    "Export data": "导出数据",
    "Copy command": "复制命令",
    "Slack Community": "Slack 社区",
    "New project": "新建项目",
    "Danger Zone": "危险操作区",
    "Add Webhook": "添加 Webhook",
    "Save Changes": "保存更改",
    "Basic auth pass": "基础认证密码",
    "Add Target Storage": "添加目标存储",
    "Bucket Name": "存储桶名称",
    "Bucket name is required": "请填写存储桶名称",
    "Path is required": "请填写路径",
    "Update Preview": "更新预览",
    "Computer Vision": "计算机视觉",
    "Expected Input Preview": "预期输入预览",
    "Try Label Studio Starter Cloud, optimized for small teams and projects.": "试试专为小团队和小项目优化的 Label Studio Starter Cloud。",
    "Runtime error": "运行时错误",
    "My Sample Project": "我的示例项目",
    "model 0": "模型 0",
    "Sequential sampling": "顺序采样",
    "The page or resource you were looking for does not exist.": "您访问的页面或资源不存在。",
    "MultiProvider: Missing providers prop": "MultiProvider：缺少 providers 属性",
    "MultiProvider: Missing children": "MultiProvider：缺少 children",
    "Breadcrumbs must be initialized first": "必须先初始化面包屑导航",
    "Crumb must have a key": "面包屑必须包含 key",
    "Project has been created and is ready for configuration": "项目已创建，可以开始配置",
    "In Progress": "进行中",
    "Annotation work is in progress on this project": "该项目正在进行标注工作",
    "Task is being annotated": "任务正在被标注",
    "All work on this project is completed": "该项目的工作已全部完成",
    "Task has been completed": "任务已完成",
    "Optional description of your project": "项目的可选描述",
    "Labeling Setup": "标注配置",
    "Cancel project creation": "取消创建项目",
    "Task ID:": "任务 ID：",
    "Project ID:": "项目 ID：",
    "Back to projects": "返回项目列表",
    "Labeling Instructions": "标注说明",
    "Read more about supported export formats in the Documentation.": "更多支持的导出格式请参阅文档。",
    "API Documentation": "API 文档",
    "Release Notes": "版本发布说明",
    "LabelStud.io Blog": "LabelStud.io 博客",
    "Create Project": "创建项目",
    "Invite Members": "邀请成员",
    "Learn, explore and get help": "学习、探索并获取帮助",
    "Heidi looking for projects": "Heidi 正在查找项目",
    "Project options": "项目选项",
    "Annotation Settings": "标注设置",
    "Show before labeling": "标注前显示",
    "Use predictions to prelabel tasks": "使用预测结果预标注任务",
    "Save annotation settings": "保存标注设置",
    "Cache reset successfully": "缓存重置成功",
    "All tabs dropped successfully": "所有标签页已关闭",
    "Project deleted successfully": "项目已删除",
    "Reset Cache may help in cases like if you are unable to modify the labeling configuration due": "如果因现有标签的校验错误而无法修改标注配置，但你能确认这些标签并不存在，重置缓存可能会有所帮助。",
    "to validation errors concerning existing labels, but you are confident that the labels don't exist. You can": "你可以",
    "use this action to reset the cache and try again.": "使用此操作重置缓存后重试。",
    "If the Data Manager is not loading, dropping all Data Manager tabs can help.": "如果数据管理器无法加载，关闭所有数据管理器标签页可能会有所帮助。",
    "Deleting a project removes all tasks, annotations, and project data from the database.": "删除项目会从数据库中移除所有任务、标注和项目数据。",
    "Tasks are ordered by Task ID": "任务按任务 ID 排序",
    "Tasks are chosen with uniform random": "任务采用均匀随机抽样",
    "Project Name": "项目名称",
    "Task Sampling": "任务抽样",
    "Available on Label Studio Enterprise": "仅 Label Studio Enterprise 可用",
    "Save general settings": "保存常规设置",
    "Labeling Interface Settings": "标注界面设置",
    "Labeling Interface": "标注界面",
    "Cancel webhook deletion": "取消删除 Webhook",
    "Confirm webhook deletion": "确认删除 Webhook",
    "Payload URL": "回调 URL",
    "Add Header": "添加请求头",
    "Remove Header": "移除请求头",
    "Send payload": "发送载荷",
    "Send for all actions": "所有事件都发送",
    "Delete webhook": "删除 Webhook",
    "Cancel webhook edit": "取消编辑 Webhook",
    "New Webhook": "新建 Webhook",
    "Edit Webhook": "编辑 Webhook",
    "app name": "应用名称",
    "Add your first webhook": "添加第一个 Webhook",
    "Setup integrations that subscribe to certain events using Webhooks. When an event is triggered, Label Studio sends an HTTP POST request to the configured webhook URL.": "使用 Webhook 配置集成来订阅特定事件。事件触发时，Label Studio 会向配置的 Webhook URL 发送 HTTP POST 请求。",
    "Learn more about webhooks (opens in new window)": "了解更多 Webhook 信息（在新窗口打开）",
    "Webhooks Settings": "Webhook 设置",
    "No model or predictions available": "没有可用的模型或预测",
    "Please select model or predictions": "请选择模型或预测",
    "Enter a name": "请输入名称",
    "Backend URL": "后端 URL",
    "Select authentication method": "选择认证方式",
    "No Authentication": "无认证",
    "Basic Authentication": "基础认证",
    "Basic auth user": "基础认证用户名",
    "Any extra params to pass during model connection": "连接模型时传递的附加参数",
    "Interactive preannotations": "交互式预标注",
    "If enabled some labeling tools will send requests to the ML Backend interactively during the annotation process.": "启用后，部分标注工具会在标注过程中交互式地向 ML 后端发送请求。",
    "Save machine learning form": "保存机器学习表单",
    "add new": "新增",
    "Delete ML Backend": "删除 ML 后端",
    "Machine learning model options": "机器学习模型选项",
    "Model Settings": "模型设置",
    "Start Model Training": "开始模型训练",
    "Test Request": "测试请求",
    "Let's connect your first model": "连接你的第一个模型",
    "Connect a machine learning model to generate live predictions for your project. Compare predictions, accelerate labeling with automatic prelabeling, and direct your team to the most impactful tasks through active learning.": "连接机器学习模型，为你的项目生成实时预测。比较预测结果，通过自动预标注加速标注，并通过主动学习引导团队优先处理最有价值的任务。",
    "Add machine learning model": "添加机器学习模型",
    "Learn more about machine learning models (opens in new window)": "了解更多机器学习模型信息（在新窗口打开）",
    "Start model training on annotation submission": "提交标注后开始模型训练",
    "This option will send a request to /train with information about annotations. You can use this to enable an Active Learning loop. You can also manually start training through model menu in its card.": "此选项会向 /train 发送包含标注信息的请求，可用于启用主动学习循环。你也可以通过模型卡片中的模型菜单手动开始训练。",
    "Save machine learning settings": "保存机器学习设置",
    "Delete Predictions": "删除预测",
    "Model version is undefined. Likely means that model_version field was missing when predictions were imported.": "模型版本未定义。这通常表示导入预测时缺少 model_version 字段。",
    "Predictions Settings": "预测设置",
    "No predictions uploaded yet": "尚未上传预测",
    "Upload predictions to automatically prelabel your data and speed up annotation. Import predictions from multiple model versions to compare their performance, or connect live models from the Model page to generate predictions on demand.": "上传预测可自动预标注数据并加快标注速度。导入多个模型版本的预测以比较效果，或从模型页连接实时模型按需生成预测。",
    "Learn more about predictions (opens in new window)": "了解更多预测信息（在新窗口打开）",
    "Storage options": "存储选项",
    "Sync Storage": "同步存储",
    "Storage Type": "存储类型",
    "Test storage connection": "测试存储连接",
    "Save storage settings": "保存存储设置",
    "Add storage": "添加存储",
    "Add Storage": "添加存储",
    "Deleting storage": "正在删除存储",
    "Cloud Storage Settings": "云存储设置",
    "Source Cloud Storage": "源云存储",
    "Target Cloud Storage": "目标云存储",
    "Add your first cloud storage": "添加第一个云存储",
    "Use cloud or database storage as the source for your labeling tasks or the target of your completed annotations.": "使用云存储或数据库存储作为标注任务的来源，或作为已完成标注的存放目标。",
    "Learn more about cloud storage (opens in new window)": "了解更多云存储信息（在新窗口打开）",
    "Cloud Storage": "云存储",
    "Storage Sync Error Log": "存储同步错误日志",
    "Learn more about cloud storage troubleshooting": "了解更多云存储故障排查",
    "Initialized: storage was added, but never synced; sufficient for starting URI link resolving": "已初始化：存储已添加但从未同步；足以开始解析 URI 链接",
    "Queued: sync job is in the queue, but not yet started": "排队中：同步任务已入队，但尚未开始",
    "In progress: sync job is running": "进行中：同步任务正在运行",
    "Failed: sync job stopped, some errors occurred": "失败：同步任务已停止，发生了一些错误",
    "Completed with errors: sync job completed but some tasks had validation errors": "已完成但有错误：同步任务已完成，但部分任务存在校验错误",
    "Completed: sync job completed successfully": "已完成：同步任务成功完成",
    "Completed with errors": "已完成但有错误",
    "Last Sync": "上次同步",
    "Not synced yet": "尚未同步",
    "Configure your Azure Blob Storage connection with all required Label Studio settings": "使用所有必需的 Label Studio 设置配置 Azure Blob Storage 连接",
    "Container Name": "容器名称",
    "Container name is required": "请填写容器名称",
    "Account Name": "账户名称",
    "Account Key": "账户密钥",
    "Your storage account key": "你的存储账户密钥",
    "Configure your Azure Blob Storage connection using Service Principal authentication for enhanced security (proxy only)": "使用服务主体认证配置 Azure Blob Storage 连接以增强安全性（仅代理模式）",
    "Configure your Databricks Unity Catalog Volumes connection with all required settings (proxy only)": "使用所有必需的设置配置 Databricks Unity Catalog Volumes 连接（仅代理模式）",
    "Configure your Google Cloud Storage connection with all required Label Studio settings": "使用所有必需的 Label Studio 设置配置 Google Cloud Storage 连接",
    "Google Application Credentials": "Google 应用凭据",
    "Paste the contents of credentials.json in this field OR leave it blank to use ADC.": "在此字段粘贴 credentials.json 的内容，或留空以使用 ADC。",
    "Google Project ID": "Google 项目 ID",
    "Leave blank to inherit from Google Application Credentials.": "留空则从 Google 应用凭据继承。",
    "Configure your Google Cloud Storage connection with Workload Identity Federation authentication (proxy only)": "使用工作负载身份联合认证配置 Google Cloud Storage 连接（仅代理模式）",
    "Local Files": "本地文件",
    "Configure your local file storage connection with all required Label Studio settings": "使用所有必需的 Label Studio 设置配置本地文件存储连接",
    "Absolute local path": "本地绝对路径",
    "Configure your Redis storage connection with all required Label Studio settings": "使用所有必需的 Label Studio 设置配置 Redis 存储连接",
    "Database Number (db)": "数据库编号（db）",
    "Your redis password": "你的 Redis 密码",
    "Host is required": "请填写主机地址",
    "Configure your AWS S3 connection with all required Label Studio settings": "使用所有必需的 Label Studio 设置配置 AWS S3 连接",
    "Region Name": "区域名称",
    "us-east-1 (default)": "us-east-1（默认）",
    "S3 Endpoint": "S3 端点",
    "Access Key ID": "访问密钥 ID",
    "Access Key ID is required": "请填写访问密钥 ID",
    "Secret Access Key": "秘密访问密钥",
    "Secret Access Key is required": "请填写秘密访问密钥",
    "Session Token": "会话令牌",
    "Session token (optional)": "会话令牌（可选）",
    "Configure your AWS S3 connection using IAM role access for enhanced security (proxy only)": "使用 IAM 角色访问配置 AWS S3 连接以增强安全性（仅代理模式）",
    "Invite members": "邀请成员",
    "Refresh invite link": "刷新邀请链接",
    "Copy invite link": "复制邀请链接",
    "Copy link": "复制链接",
    "API Token Settings": "API 令牌设置",
    "API Token settings saved": "API 令牌设置已保存",
    "Show API token settings": "显示 API 令牌设置",
    "Invite new member": "邀请新成员",
    "Close user details": "关闭用户详情",
    "Create new model": "创建新模型",
    "delete label": "删除标签",
    "Add choices": "添加选项",
    "Add label names": "添加标签名称",
    "Add labels": "添加标签",
    "Drag to resize. Double-click to collapse or expand.": "拖动调整大小，双击折叠或展开。",
    "Bbox object detection": "目标框检测",
    "Polygon labeling": "多边形标注",
    "Select label and click on image to start": "选择标签后点击图像开始",
    "Named entity recognition": "命名实体识别",
    "Width of region borders": "区域边框宽度",
    "Allow image zoom (ctrl+wheel)": "允许图像缩放（Ctrl+滚轮）",
    "Show controls to zoom in and out": "显示放大缩小控件",
    "Show controls to rotate image": "显示旋转图像控件",
    "Select text by words": "按词选择文本",
    "Display labels:": "显示标签：",
    "Add filter for long list of labels": "为长标签列表添加筛选",
    "Enterprise feature - Available in Label Studio Enterprise": "企业版功能 - 在 Label Studio Enterprise 中可用",
    "Create custom template": "创建自定义模板",
    "Save and Leave": "保存并离开",
    "Save changes": "保存更改",
    "You have unsaved changes.": "你有未保存的更改。",
    "Would you like to save them before leaving?": "离开前是否保存？",
    "Discard and leave": "放弃并离开",
    "Imported file is too big": "导入的文件过大",
    "Dataset URL": "数据集 URL",
    "Add URL": "添加 URL",
    "Upload file": "上传文件",
    "Video format support depends on your browser. Click to learn more.": "视频格式支持取决于你的浏览器，点击了解更多。",
    "Learn more about video format support (opens in a new tab)": "了解视频格式支持详情（在新标签页打开）",
    "Cloud Storage documentation (opens in a new tab)": "云存储文档（在新标签页打开）",
    "Upload limitations documentation (opens in a new tab)": "上传限制文档（在新标签页打开）",
    "Multi-image labeling documentation (opens in a new tab)": "多图像标注文档（在新标签页打开）",
    "Import data": "导入数据",
    "Cancel import": "取消导入",
    "Finish import": "完成导入",
    "Can't prepare sample data.": "无法准备示例数据。",
    "No sample task data available.": "没有可用的示例任务数据。",
    "Draft saved successfully": "草稿保存成功",
    "There was an error saving your draft": "保存草稿时出错",
    "Heidi's down": "Heidi 出故障了",
    "Copy error stacktrace": "复制错误堆栈",
    "Copy Stacktrace": "复制堆栈",
    "Go back": "返回",
    "Reload page": "重新加载页面",
    "got ya, suspicious hacker!": "抓到你了，可疑的黑客！",
    "Submit form": "提交表单",
    "Response Parser only accepts function as a child": "Response Parser 只接受函数作为子元素",
    "It's easier to find the projects when you organize them into workspaces using Label Studio Enterprise.": "使用 Label Studio Enterprise 将项目整理到工作区后，查找项目会更轻松。",
    "Unlock faster access provisioning": "解锁更快的权限配置",
    "Streamline assigning staff to multiple projects by assigning them to workspaces in Label Studio Enterprise.": "在 Label Studio Enterprise 中通过将成员分配到工作区，简化为成员分配多个项目的流程。",
    "In the Enterprise platform, admins can view annotator performance dashboards to optimize resource allocation, improve team management, and inform compensation.": "在企业版平台中，管理员可以查看标注员绩效看板，以优化资源分配、改进团队管理并为薪酬决策提供依据。",
    "You can control access to specific projects and workspaces for internal team members and external annotators using Label Studio Enterprise.": "你可以使用 Label Studio Enterprise 控制内部团队成员和外部标注员对特定项目和工作区的访问权限。",
    "You can use or modify dozens or templates to configure your labeling UI, or create a custom configuration from scratch using simple XML-like tag.": "你可以使用或修改数十种模板来配置标注界面，也可以使用类似 XML 的简单标签从零创建自定义配置。",
    "Labeling for GenAI": "生成式 AI 标注",
    "Label Studio has templates available for supervised LLM fine-tuning, RAG retrieval ranking, RLHF, chatbot evaluation, and more.": "Label Studio 提供适用于监督式 LLM 微调、RAG 检索排序、RLHF、聊天机器人评估等的模板。",
    "Explore templates": "浏览模板",
    "It looks like your team is growing!": "看起来你的团队正在壮大！",
    "Assign roles to your team using Label Studio Enterprise and control access to sensitive data at the project and workspace levels.": "使用 Label Studio Enterprise 为团队分配角色，并在项目和工作区级别控制对敏感数据的访问。",
    "Want to simplify and secure logging in?": "想简化并加固登录流程吗？",
    "Enable Single Sign-On for your team using SAML, SCIM2 or LDAP with Label Studio Enterprise.": "使用 Label Studio Enterprise 的 SAML、SCIM2 或 LDAP 为团队启用单点登录。",
    "Want to automate task distribution?": "想自动化任务分配吗？",
    "Create rules, automate how tasks are distributed to annotators, and only show tasks assigned to each annotator in their view.and control task visibility for each annotator.": "创建规则，自动化任务分配给标注员的方式，并在每个标注员的视图中只显示分配给他们的任务，同时控制每个标注员的任务可见性。",
    "Share knowledge with the community": "与社区分享知识",
    "Have questions or a tip to share with other Label Studio users? Join the community slack channel for the latest updates.": "有其他 Label Studio 用户请教问题或想分享技巧？加入社区 Slack 频道获取最新动态。",
    "Join the community": "加入社区",
    "Label Studio supports multiple points of integration with cloud storage, machine learning models, and popular tools to automate your machine learning pipeline.": "Label Studio 支持与云存储、机器学习模型和常用工具进行多方位集成，帮助自动化你的机器学习流水线。",
    "Check out the integrations directory": "查看集成目录",
    "Apply your AWS spend to Label Studio Enterprise": "将 AWS 消费额度用于 Label Studio Enterprise",
    "Label Studio Enterprise is now available on the AWS Marketplace so you can use your committed spend to streamline data labeling workflows.": "Label Studio Enterprise 现已上架 AWS Marketplace，你可以使用承诺消费额度来优化数据标注工作流。",
    "Save time with Auto-Labeling": "使用自动标注节省时间",
    "Use automation to instantly label large-scale datasets without sacrificing quality in the Enterprise platform.": "在企业版平台中使用自动化即时标注大规模数据集，同时不牺牲质量。",
    "You can increase the quality of your labeled data with reviewer workflows and task agreement scores using Label Studio Enterprise.": "使用 Label Studio Enterprise 的审核工作流和任务一致性评分提升标注数据质量。",
    "Evaluate GenAI models": "评估生成式 AI 模型",
    "Combine automation plus human supervision to evaluate and ensure LLM quality in the Enterprise platform.": "在企业版平台中结合自动化与人工监督，评估并保障 LLM 质量。",
    "You can save time managing infrastructure and upgrades, plus access more features for automation, quality, and team management, by using the Enterprise cloud service.": "使用企业版云服务可节省基础设施和升级管理时间，并解锁更多自动化、质量和团队管理功能。",
    "You can connect ML models using the backend SDK to save time with pre-labeling or active learning.": "你可以使用后端 SDK 连接 ML 模型，通过预标注或主动学习节省时间。",
    "Don't show": "不再显示",
    "Failed to load live Heidi tips collection": "加载实时 Heidi 提示集合失败",
    "Label Studio Logo": "Label Studio 标志",
    "Keyboard Shortcuts": "键盘快捷键",
    "Account & Settings": "账户与设置",
    "Dark Mode": "深色模式",
    "Log Out": "退出登录",
    "Unpin menu": "取消固定菜单",
    "Pin menu": "固定菜单",
    "Label Studio Frontend doesn't exist on the page": "页面上不存在 Label Studio 前端",
    "Service Worker registered with scope:": "Service Worker 已注册，作用域：",
    "Service Worker registration failed:": "Service Worker 注册失败：",
    "You are about to reset the cache for": "你即将重置以下项目的缓存：",
    "You are about to drop all tabs for": "你即将关闭以下项目的所有标签页：",
    "You are about to delete the project": "你即将删除项目：",
    "This template requires more data then you have for now": "此模板需要的数据多于你当前拥有的数据",
    "Your labeling configuration is empty. It is required to label your data.": "你的标注配置为空，而配置是标注数据的必要条件。",
    "Write instructions to help users complete labeling tasks.": "编写说明，帮助用户完成标注任务。",
    "Enable and select which set of predictions to use for prelabeling.": "启用并选择用于预标注的预测集。",
    "Build a high quality model to auto-label your data using LLMs": "使用 LLM 构建高质量模型，自动标注你的数据",
    "Select which predictions or which model you want to use:": "选择要使用的预测或模型：",
    "You can export dataset in one of the following formats:": "你可以使用以下格式之一导出数据集：",
    "Files are being prepared. It might take long time.": "文件正在准备中，可能需要较长时间。",
    "Project was deleted or not yet created": "项目已被删除或尚未创建",
    "Contact your administrator to create Webhooks": "请联系管理员创建 Webhook",
    "Please check new notification settings in the Account & Settings page": "请检查“账户与设置”页面中的新通知设置",
    "Local file serving is disabled": "本地文件服务已禁用",
    "Sample config to label with bboxes": "使用边界框标注的示例配置",
    "You can configure labels and their colors": "你可以配置标签及其颜色",
    "Simple object detection": "简单目标检测",
    "Use new line as a separator to add multiple labels": "使用换行符分隔可添加多个标签",
    "read about the available tags in our documentation": "在文档中了解可用标签",
    "1. Navigate to the": "1. 进入",
    "2. Select the desired tasks.": "2. 选择所需任务。",
    "3. Click on": "3. 点击",
    "Batch predictions": "批量预测",
    "from the": "从",
    "menu.": "菜单。",
    "Treat CSV/TSV as": "将 CSV/TSV 视为",
    "Time Series or Whole Text File": "时间序列或完整文本文件",
    "Drag & drop files here": "将文件拖放到此处",
    "or click to browse": "或点击浏览",
    "HTML / HyperText": "HTML / 超文本",
    "Structured data": "结构化数据",
    "Important:": "重要：",
    "upload limitations": "上传限制",
    ". JSONL or Parquet (Enterprise only) files require cloud storage.": "。JSONL 或 Parquet（仅企业版）文件需要云存储。",
    "import preannotated data": "导入预标注数据",
    "View JSON input format": "查看 JSON 输入格式",
    "labeling configuration": "标注配置",
    "Import Data": "导入数据",
    "Ask on Slack": "在 Slack 提问",
    "Go Back": "返回",
    "Reload": "重新加载",
    "Export timed out": "导出超时",
    "Recommended options:": "推荐选项：",
    "console command": "控制台命令",
    "export snapshots via the SDK": "通过 SDK 导出快照",
    "Export timeout in Community Edition": "社区版导出超时",
    "CLI/SDK export options": "CLI/SDK 导出选项",
    "Repository": "代码仓库",
    "Enterprise": "企业版",
    "Create one and start labeling your data.": "创建一个项目并开始标注你的数据。",
    "Is Active": "是否启用",
    "Send Payload for": "发送载荷事件：",
    "Validate and Save": "验证并保存",
    "Send Test Request": "发送测试请求",
    "Disconnected": "未连接",
    "Connected": "已连接",
    "Training": "训练中",
    "Predicting": "预测中",
    "Connect Model": "连接模型",
    "Data Manager": "数据管理器",
    "Actions": "操作",
    "Annotation settings": "标注设置",
    "Predictions List": "预测列表",
    "Check Connection": "检查连接",
    "See docs": "查看文档",
    "Local Storage documentation": "本地存储文档",
    "Reset Link": "重置链接",
    "Last Activity": "最近活动",
    "Created Projects": "创建的项目",
    "Contributed to": "参与贡献",
    "Create a Model": "创建模型",
    "Start Training": "开始训练",
    "Delete Webhook": "删除 Webhook",
    "Webhooks": "Webhook",
    "Enterprise Feature": "企业版功能",
    "Workspace": "工作区",
    "Data Import": "数据导入",
    "Instructions": "说明",
    "Prelabeling": "预标注",
    "General Settings": "常规设置",
    "Create Model": "创建模型",
    "Import Data": "导入数据",
    "Slack": "Slack",
    "Copied": "已复制",
    "Preview": "预览",
    "Browse Templates": "浏览模板",
    "See all tags": "查看所有标签",
    "Configure settings": "配置设置",
    "Configure data": "配置数据",
    "Arrow Icon": "箭头图标",
    "Custom template": "自定义模板",
    "contribute a template": "贡献模板",
    "List of tasks": "任务列表",
    "Images": "图像",
    "Audio": "音频",
    "Video": "视频",
    "Text": "文本",
    "PDF": "PDF",
    "Sample": "示例",
    "Add": "添加",
    "Edit": "编辑",
    "Delete": "删除",
    "Save": "保存",
    "Cancel": "取消",
    "Create": "创建",
    "Close": "关闭",
    "Settings": "设置",
    "Label": "标注",
    "Email": "邮箱",
    "Name": "姓名",
    "Model": "模型",
    "Predictions": "预测",
    "Error": "错误",
    "Description": "描述",
    "Project Name": "项目名称",
    ". This action cannot be undone.": "。此操作无法撤销。",
    "You are about to reset the cache for": "你即将重置以下项目的缓存：",
    "Account &amp; Settings": "账户与设置",
    "API Tokens Settings": "API 令牌设置",
    "Add Members": "添加成员",
    "Back to projects": "返回项目列表",
    "multi-image labeling": "多图像标注",
    "sends an HTTP POST request to the configured webhook URL.": "向配置的 Webhook URL 发送 HTTP POST 请求。",
    "for troubleshooting tips on cloud storage connections.": "获取云存储连接故障排查提示。",
    "(View Logs)": "（查看日志）",
    "first to preview the expected JSON data format": "首先预览预期的 JSON 数据格式",
    "for background exports at scale.": "用于大规模后台导出。",
    "to create and download a snapshot without relying on a single UI request.": "无需依赖单次 UI 请求即可创建并下载快照。",
    "since it is designed for large-scale projects and asynchronous exports.": "因为它专为大型项目和异步导出而设计。",
    "<imported file>": "导入的文件",
    "<set manually>": "手动设置",
    "Parser error": "解析错误",
    "Browse templates": "浏览模板",
    "Save configuration": "保存配置",
    "Template parsing error:": "模板解析错误：",
    "https://s3.amazonaws.com (default)": "https://s3.amazonaws.com（默认）",
}

# JSX 文本节点翻译表（不带引号）
TEXT_DICT = {
    "Welcome 👋": "欢迎 👋",
    "Let's get you started.": "让我们开始吧。",
    "Recent Projects": "最近项目",
    "View All": "查看全部",
    "Create your first project": "创建你的第一个项目",
    "Import your data and set up the labeling interface to start annotating": "导入数据并配置标注界面，即可开始标注",
    "Create Project": "创建项目",
    "Resources": "资源",
    "Learn, explore and get help": "学习、探索并获取帮助",
    "Label Studio Version: Community": "Label Studio 版本：社区版",
    "Error occurred": "发生错误",
    "Runtime error": "运行时错误",
    "Home": "首页",
    "Learn more": "了解更多",
    "Cancel": "取消",
    "Delete": "删除",
    "Enterprise Feature": "企业版功能",
    "Save": "保存",
    ". This action cannot be undone.": "。此操作无法撤销。",
    "Edit": "编辑",
    "Project Name": "项目名称",
    "Workspace": "工作区",
    "Delete Webhook": "删除 Webhook",
    "Webhooks": "Webhook",
    "Add Webhook": "添加 Webhook",
    "Start Training": "开始训练",
    "Create a Model": "创建模型",
    "Description": "描述",
    "Data Import": "数据导入",
    "Project was deleted or not yet created": "项目已被删除或尚未创建",
    "Instructions": "说明",
    "Files are being prepared. It might take long time.": "文件正在准备中，可能需要较长时间。",
    "You can export dataset in one of the following formats:": "你可以使用以下格式之一导出数据集：",
    "Slack": "Slack",
    "Repository": "代码仓库",
    "CLI/SDK export options": "CLI/SDK 导出选项",
    "Enterprise": "企业版",
    "Export timed out": "导出超时",
    "Recommended options:": "推荐选项：",
    "console command": "控制台命令",
    "Copied": "已复制",
    "export snapshots via the SDK": "通过 SDK 导出快照",
    "Label Studio Enterprise": "Label Studio Enterprise",
    "Export timeout in Community Edition": "社区版导出超时",
    "Create": "创建",
    "Create one and start labeling your data.": "创建一个项目并开始标注你的数据。",
    "Settings": "设置",
    "Label": "标注",
    "Annotation Settings": "标注设置",
    "Labeling Instructions": "标注说明",
    "Write instructions to help users complete labeling tasks.": "编写说明，帮助用户完成标注任务。",
    "Prelabeling": "预标注",
    "Enable and select which set of predictions to use for prelabeling.": "启用并选择用于预标注的预测集。",
    "You are about to reset the cache for": "你即将重置以下项目的缓存：",
    "You are about to drop all tabs for": "你即将关闭以下项目的所有标签页：",
    "You are about to delete the project": "你即将删除项目：",
    "Danger Zone": "危险操作区",
    "General Settings": "常规设置",
    "Is Active": "是否启用",
    "Send Payload for": "发送载荷事件：",
    "Contact your administrator to create Webhooks": "请联系管理员创建 Webhook",
    "Select which predictions or which model you want to use:": "选择要使用的预测或模型：",
    "Validate and Save": "验证并保存",
    "Send Test Request": "发送测试请求",
    "Disconnected": "未连接",
    "Connected": "已连接",
    "Error": "错误",
    "Training": "训练中",
    "Predicting": "预测中",
    "Model": "模型",
    "Connect Model": "连接模型",
    "1. Navigate to the": "1. 进入",
    "Data Manager": "数据管理器",
    "2. Select the desired tasks.": "2. 选择所需任务。",
    "3. Click on": "3. 点击",
    "Batch predictions": "批量预测",
    "from the": "从",
    "Actions": "操作",
    "menu.": "菜单。",
    "Annotation settings": "标注设置",
    "Predictions": "预测",
    "Predictions List": "预测列表",
    "Sync Storage": "同步存储",
    "Connection failed": "连接失败",
    "Check Connection": "检查连接",
    "Cloud Storage": "云存储",
    "Google Cloud Storage": "Google Cloud Storage",
    "Azure Blob Storage": "Azure Blob Storage",
    "Add Source Storage": "添加源存储",
    "Add Target Storage": "添加目标存储",
    "See docs": "查看文档",
    "Close": "关闭",
    "Local file serving is disabled": "本地文件服务已禁用",
    "Local Storage documentation": "本地存储文档",
    "Create Model": "创建模型",
    "Reset Link": "重置链接",
    "Email": "邮箱",
    "Name": "姓名",
    "Last Activity": "最近活动",
    "Created Projects": "创建的项目",
    "Contributed to": "参与贡献",
    "Build a high quality model to auto-label your data using LLMs": "使用 LLM 构建高质量模型，自动标注你的数据",
    "Your labeling configuration is empty. It is required to label your data.": "你的标注配置为空，而配置是标注数据的必要条件。",
    "read about the available tags in our documentation": "在文档中了解可用标签",
    "Use new line as a separator to add multiple labels": "使用换行符分隔可添加多个标签",
    "Add": "添加",
    "Configure settings": "配置设置",
    "Configure data": "配置数据",
    "This template requires more data then you have for now": "此模板需要的数据多于你当前拥有的数据",
    "See all tags": "查看所有标签",
    "Browse Templates": "浏览模板",
    "Preview": "预览",
    "Simple object detection": "简单目标检测",
    "Sample config to label with bboxes": "使用边界框标注的示例配置",
    "You can configure labels and their colors": "你可以配置标签及其颜色",
    "Arrow Icon": "箭头图标",
    "Custom template": "自定义模板",
    "contribute a template": "贡献模板",
    "Treat CSV/TSV as": "将 CSV/TSV 视为",
    "List of tasks": "任务列表",
    "Time Series or Whole Text File": "时间序列或完整文本文件",
    "Drag & drop files here": "将文件拖放到此处",
    "or click to browse": "或点击浏览",
    "Images": "图像",
    "Audio": "音频",
    "Video": "视频",
    "HTML / HyperText": "HTML / 超文本",
    "Text": "文本",
    "Structured data": "结构化数据",
    "PDF": "PDF",
    "Important:": "重要：",
    "upload limitations": "上传限制",
    ". JSONL or Parquet (Enterprise only) files require cloud storage.": "。JSONL 或 Parquet（仅企业版）文件需要云存储。",
    "import preannotated data": "导入预标注数据",
    "Sample": "示例",
    "View JSON input format": "查看 JSON 输入格式",
    "labeling configuration": "标注配置",
    "Import Data": "导入数据",
    "Ask on Slack": "在 Slack 提问",
    "Go Back": "返回",
    "Reload": "重新加载",
    "Please check new notification settings in the Account & Settings page": "请检查“账户与设置”页面中的新通知设置",
    "API Tokens Settings": "API 令牌设置",
    "Add Members": "添加成员",
    "Back to projects": "返回项目列表",
    "Cloud Storage": "云存储",
    "multi-image labeling": "多图像标注",
    "Export": "导出",
    "Import": "导入",
    "Files": "文件",
    "Available": "可用",
    "sends an HTTP POST request to the configured webhook URL.": "向配置的 Webhook URL 发送 HTTP POST 请求。",
    "for troubleshooting tips on cloud storage connections.": "获取云存储连接故障排查提示。",
    "(View Logs)": "（查看日志）",
    "first to preview the expected JSON data format": "首先预览预期的 JSON 数据格式",
    "for background exports at scale.": "用于大规模后台导出。",
    "to create and download a snapshot without relying on a single UI request.": "无需依赖单次 UI 请求即可创建并下载快照。",
    "since it is designed for large-scale projects and asynchronous exports.": "因为它专为大型项目和异步导出而设计。",
}
