# -*- coding: utf-8 -*-
"""数据管理、通用组件（datamanager/ui）与标注器常用词库。"""

DICT = {
    "Focus previous task": "聚焦上一个任务",
    "not contains": "不包含",
    "You have unsaved changes": "你有未保存的更改",
    "Discard and continue": "放弃并继续",
    "There are comments which are not persisted. Please submit the annotation. Continuing will discard these comments.": "存在尚未保存的评论。请先提交标注，继续将丢弃这些评论。",
    "DataManager store not available": "数据管理器存储不可用",
    "All fields": "所有字段",
    "Annotation overlap has been reached for this task. Your draft is preserved but cannot be submitted.": "此任务已达到标注重叠上限。你的草稿已保留，但无法提交。",
    "Error: Invalid JSON": "错误：JSON 无效",
    "Task Preview": "任务预览",
    "No tasks available": "没有可用任务",
    "Unpin filters": "取消固定筛选",
    "is between": "介于",
    "not between": "不介于",
    "Comfortable density": "舒适密度",
    "Compact density": "紧凑密度",
    "Open New Tab": "在新标签页打开",
    "Copy JSON": "复制 JSON",
    "Failed to copy to clipboard": "复制到剪贴板失败",
    "Search columns": "搜索列",
    "Filtered tasks": "已筛选任务",
    "Total tasks in the project": "项目中的任务总数",
    "Failed to copy filters:": "复制筛选失败：",
    "Clipboard does not contain valid JSON.": "剪贴板中不包含有效的 JSON。",
    "No matching filter columns found in this project. Filters may be from a different project.": "此项目中未找到匹配的筛选列，筛选条件可能来自其他项目。",
    "Another Filter": "另一个筛选",
    "Copy filters to clipboard; Tip: Use it in Label Studio SDK": "将筛选复制到剪贴板；提示：可在 Label Studio SDK 中使用",
    "Copy filters": "复制筛选",
    "Pasted!": "已粘贴！",
    "Paste filters from clipboard": "从剪贴板粘贴筛选",
    "Paste filters": "粘贴筛选",
    "Undo paste — restore previous filters": "撤销粘贴——恢复之前的筛选",
    "Undo paste": "撤销粘贴",
    "Pin to sidebar": "固定到侧边栏",
    "Pin filters to sidebar": "将筛选固定到侧边栏",
    "No tasks found": "未找到任务",
    "Try adjusting or clearing the filters to see more results": "尝试调整或清除筛选条件以查看更多结果",
    "No tasks available for review or labeling": "没有可用于审核或标注的任务",
    "Tasks imported to this project will appear here": "导入到此项目的任务将显示在这里",
    "Start labeling tasks": "开始标注任务",
    "Tasks you've labeled will appear here": "你标注过的任务将显示在这里",
    "Tasks assigned to you will appear here": "分配给你的任务将显示在这里",
    "Tasks will appear here when they become available": "任务可用时将显示在这里",
    "Import data to get your project started": "导入数据以开始使用你的项目",
    "Connect your cloud storage or upload files from your computer": "连接云存储或从你的电脑上传文件",
    "includes all": "包含全部",
    "does not include all": "不包含全部",
    "is not": "不是",
    "is empty": "为空",
    "is before": "早于",
    "is after": "晚于",
    "Select value": "选择值",
    "not equal": "不等于",
    "review assignments": "审核分配",
    "annotator assignments": "标注员分配",
    "ground truths": "基准答案",
    "Delete selected ": "删除所选",
    "Delete selected": "删除所选",
    "Destructive action": "危险操作",
    "Confirm action": "确认操作",
    "Tasks Actions": "任务操作",
    "Decrease columns number": "减少列数",
    "Increase columns number": "增加列数",
    "Grid settings": "网格设置",
    "You must upgrade your plan to import data": "你必须升级套餐才能导入数据",
    "Toggle open": "切换展开",
    "Order by": "排序方式",
    "Sort ascending": "升序排序",
    "Sort descending": "降序排序",
    "Refresh data": "刷新数据",
    "List view": "列表视图",
    "Switch to list view": "切换到列表视图",
    "Grid view": "网格视图",
    "View Task Source": "查看任务来源",
    "Customize Columns": "自定义列",
    "Tab name": "标签页名称",
    "Tab options": "标签页选项",
    "Resolve URIs": "解析 URI",
    "No content to copy": "没有可复制的内容",
    "Task ID not found": "未找到任务 ID",
    "Display as": "显示为",
    "Adjust calculation and display of all agreement columns": "调整所有一致性列的计算与显示",
    "Date Time": "日期时间",
    "Hyper Text": "超文本",
    "Time Series": "时间序列",
    "Error generating accessor": "生成访问器出错",
    "Copy (2)": "复制（2）",
    "Task ID must be provided": "必须提供任务 ID",
    "Column or id is not defined": "未定义列或 id",
    "is not a function": "不是函数",
    "is not a valid element": "不是有效元素",
    "Error parsing JSON": "解析 JSON 出错",
    "Something went wrong": "出问题了",
    "Error occurred when loading data": "加载数据时出错",
    "Your action is being processed in the background.": "你的操作正在后台处理中。",
    "Go to setup": "前往配置",
    "Before you can annotate the data, set up labeling configuration": "在标注数据之前，请先配置标注界面",
    "You're almost there!": "马上就完成了！",
    "Actions must be an array": "操作必须是数组",
    "LSF not initialized properly": "LSF 未正确初始化",
    "Error fetching actions:": "获取操作失败：",
    "Task skipped successfully": "任务已跳过",
    "Task is not skipped": "任务未跳过",
    "Task cannot be skipped": "无法跳过此任务",
    "This task cannot be skipped": "此任务无法跳过",
    "Task cannot be skipped: allow_skip is false and user lacks manager role": "无法跳过此任务：allow_skip 为 false 且用户没有管理员角色",
    "Annotation saved successfully": "标注保存成功",
    "Annotation is not saved": "标注未保存",
    "Annotation updated successfully": "标注更新成功",
    "Annotation is not updated": "标注未更新",
    "Draft is not saved": "草稿未保存",
    "Annotation must be on unskip": "取消跳过后必须提交标注",
    "Failed to initialize LabelStudio": "初始化 LabelStudio 失败",
    "Can't find task": "找不到任务",
    "Make sure that LSF was properly initialized": "请确保 LSF 已正确初始化",
    "Failed to enrich comment users:": "补充评论用户信息失败：",
    "Action must provide a unique ID": "操作必须提供唯一 ID",
    "Every action must provide a unique ID": "每个操作都必须提供唯一 ID",
    "Toggle bulk sidebar minimization": "切换批量侧边栏最小化",
    "No actions found in response or response is invalid": "响应中未找到操作或响应无效",
    "No users found in response or response is invalid": "响应中未找到用户或响应无效",
    "Oops...": "哎呀…",
    "Project has been deleted or not yet created.": "项目已被删除或尚未创建。",
    "Errors occurred": "发生错误",
    "Storage sync": "存储同步",
    "Failed to sync data": "数据同步失败",
    "Check your storage settings. You may need to recreate this dataset": "请检查存储设置，你可能需要重新创建此数据集",
    "Nothing found": "未找到内容",
    "Try adjusting the filter or similarity search parameters": "尝试调整筛选或相似度搜索参数",
    "Press the button below to see any synced records": "点击下方按钮查看已同步的记录",
    "Preview of the task image to quickly navigate through the tasks and select the ones you want to work on.": "任务图像预览，可快速浏览任务并选择要处理的任务。",
    "See docs on importing data": "查看数据导入文档",
    "(opens in a new tab)": "（在新标签页打开）",
    "Clear Filters": "清除筛选",
    "Label All Tasks": "标注所有任务",
    "Connect Cloud Storage": "连接云存储",
    "Loading actions...": "正在加载操作…",
    "Fit images to width": "图像适应宽度",
    "Label Tasks As Displayed": "按显示标注任务",
    "Click to load": "点击加载",
    "Compare All Annotations": "比较所有标注",
    "Copy Cell Contents": "复制单元格内容",
    "Copy Task ID": "复制任务 ID",
    "opossum loader": "加载中",
    "Clear Search": "清除搜索",
    "Open Reader View": "打开阅读视图",
    "Collapse panel": "收起面板",
    "Expand panel": "展开面板",
    "Unselect all rows": "取消全选行",
    "Select all rows": "全选行",
    "Unselect row": "取消选择行",
    "Select row": "选择行",
    "No items found": "未找到条目",
    "Try adjusting your search or clearing the filters to see more results.": "尝试调整搜索或清除筛选条件以查看更多结果。",
    "Clear date selection": "清除日期选择",
    "Reset date": "重置日期",
    "Close date picker": "关闭日期选择器",
    "Apply date": "应用日期",
    "days selected": "天已选择",
    "day selected": "天已选择",
    "Last 7 days": "最近 7 天",
    "Last 30 days": "最近 30 天",
    "This week": "本周",
    "This month": "本月",
    "This year": "今年",
    "All Time": "全部时间",
    "Get access to Enterprise Features": "获取企业版功能",
    "This feature is available within the Enterprise plan. Contact our sales team to get access to this and more!": "此功能属于企业版套餐。请联系销售团队获取该功能及更多内容！",
    "Contact Sales": "联系销售",
    "Search keys or values": "搜索键或值",
    "Search JSON": "搜索 JSON",
    "Reset filters": "重置筛选",
    "Plain text content": "纯文本内容",
    "Markdown content": "Markdown 内容",
    "HTML content": "HTML 内容",
    "Reader View": "阅读视图",
    "Dismiss message": "关闭消息",
    "Close modal": "关闭弹窗",
    "First page": "第一页",
    "Previous page": "上一页",
    "Next page": "下一页",
    "Last page": "最后一页",
    "Deselect all items": "取消全选",
    "Select all rendered items": "全选当前渲染的条目",
    "No results found.": "未找到结果。",
    "Click to view history": "点击查看历史",
    "Selected tags": "已选标签",
    "Search tags": "搜索标签",
    "Available options": "可用选项",
    "Show more": "显示更多",
    "Show less": "显示更少",
    "Upload Image": "上传图像",
    "Plain Text": "纯文本",
    "Markdown": "Markdown",
    "HTML": "HTML",
    "Selected items": "已选条目",
    "Select All": "全选",
    "No items selected": "未选择条目",
    "Loading...": "加载中…",
    "Any time": "任意时间",
    "Include time": "包含时间",
    "Clear": "清除",
    "Reset": "重置",
    "Apply Range": "应用范围",
    "Enter a valid time.": "请输入有效时间。",
    "date and time.": "日期和时间。",
    "date.": "日期。",
    "No options found.": "未找到选项。",
    "Failed to restore column sizes from localStorage:": "从 localStorage 恢复列宽失败：",
    "Sparkles area overlay": "闪光区域覆盖层",
    "Contact Sales": "联系销售",
    "useToast must be used within a ToastProvider": "useToast 必须在 ToastProvider 内使用",
    "Tooltip does accept a single child only": "Tooltip 只接受单个子元素",
    "[RowContextMenu] Failed to fetch full task data:": "【RowContextMenu】获取完整任务数据失败：",
}

TEXT = {
    "Unable to play": "无法播放",
    "Where": "位置",
    "Review": "审核",
    "Next Task": "下一个任务",
    "contact our team": "联系我们的团队",
    "Oops...": "哎呀…",
    "Project has been deleted or not yet created.": "项目已被删除或尚未创建。",
    "True": "是",
    "False": "否",
    "Errors occurred": "发生错误",
    "Storage sync": "存储同步",
    "Tasks:": "任务：",
    "No filters applied": "未应用筛选",
    "Back": "返回",
    "Failed to sync data": "数据同步失败",
    "Nothing found": "未找到内容",
    "Refresh": "刷新",
    "Clear Filters": "清除筛选",
    "Label All Tasks": "标注所有任务",
    "Connect Cloud Storage": "连接云存储",
    "Filters": "筛选",
    "Loading actions...": "正在加载操作…",
    "Fit images to width": "图像适应宽度",
    "Label Tasks As Displayed": "按显示标注任务",
    "Tasks": "任务",
    "Annotations": "标注",
    "Click to load": "点击加载",
    "Code": "代码",
    "Interactive": "交互式",
    "Compare All Annotations": "比较所有标注",
    "Copy Cell Contents": "复制单元格内容",
    "Copy Task ID": "复制任务 ID",
    "View Task Source": "查看任务来源",
    "Performance": "性能",
    "and": "和",
    "Upload Image": "上传图像",
    "Plain Text": "纯文本",
    "Markdown": "Markdown",
    "HTML": "HTML",
    "Selected items": "已选条目",
    "Select All": "全选",
    "No items selected": "未选择条目",
    "Loading...": "加载中…",
    "Any time": "任意时间",
    "Include time": "包含时间",
    "Clear": "清除",
    "Reset": "重置",
    "Apply Range": "应用范围",
    "No options found.": "未找到选项。",
    "Check your storage settings. You may need to recreate this dataset": "请检查存储设置，你可能需要重新创建此数据集",
    "Try adjusting the filter or similarity search parameters": "尝试调整筛选或相似度搜索参数",
    "Press the button below to see any synced records": "点击下方按钮查看已同步的记录",
    "Preview of the task image to quickly navigate through the tasks and select the ones you want to work on.": "任务图像预览，可快速浏览任务并选择要处理的任务。",
    "See docs on importing data": "查看数据导入文档",
    "(opens in a new tab)": "（在新标签页打开）",
    "date.": "日期。",
    "date and time.": "日期和时间。",
    "Enter a valid time.": "请输入有效时间。",
}
