# Generated by Django 5.1.15 on 2026-08-13 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
        ("projects", "0034_project_annotator_evaluation_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("TextClassification", "TextClassification"),
                            ("NamedEntityRecognition", "NamedEntityRecognition"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("HF", "HuggingFace Transformers"),
                            ("SKLEARN", "scikit-learn"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "local_path",
                    models.CharField(
                        help_text="本地模型目录绝对路径（事先下载，不联网）",
                        max_length=1024,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "default_config",
                    models.JSONField(default=dict, help_text="默认超参"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "training_base_model",
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "train_subset",
                    models.CharField(
                        choices=[
                            ("All", "All tasks"),
                            ("HasGT", "Tasks with ground truth annotations"),
                            ("Sample", "Random sample of annotated tasks"),
                        ],
                        default="HasGT",
                        max_length=16,
                    ),
                ),
                (
                    "hyperparams",
                    models.JSONField(
                        default=dict,
                        help_text="用户覆盖的超参，merge 到 base_model.default_config",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Running", "Running"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Pending",
                        max_length=16,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict, help_text="训练指标：{epoch, loss, acc, ...}"
                    ),
                ),
                (
                    "artifact_path",
                    models.CharField(
                        blank=True,
                        help_text="训练产物本地目录绝对路径",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True,
                        help_text='写入 Prediction.model_version，格式 f"{base_model.name}__{job.id}"',
                        max_length=255,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "base_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="training.basemodel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "training_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_subset",
                    models.CharField(
                        choices=[
                            ("All", "All tasks"),
                            ("HasGT", "Tasks with ground truth annotations"),
                            ("Sample", "Random sample of annotated tasks"),
                        ],
                        default="HasGT",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Running", "Running"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Pending",
                        max_length=16,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="测试指标：{accuracy, f1, precision, recall, confusion_matrix, total, correct, skipped}",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "base_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="零样本测试（与 training_job 二选一）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_runs",
                        to="training.basemodel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to="projects.project",
                    ),
                ),
                (
                    "training_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="训练产物测试（与 base_model 二选一）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_runs",
                        to="training.trainingjob",
                    ),
                ),
            ],
            options={
                "db_table": "training_test_run",
                "ordering": ["-created_at"],
            },
        ),
    ]
