# Generated by Django 5.1.15 on 2026-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='framework',
            field=models.CharField(choices=[('HF', 'HuggingFace Transformers'), ('SKLEARN', 'scikit-learn'), ('YOLO', 'Ultralytics YOLO')], max_length=16),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='task_type',
            field=models.CharField(choices=[('TextClassification', 'TextClassification'), ('NamedEntityRecognition', 'NamedEntityRecognition'), ('ObjectDetection', 'ObjectDetection'), ('InstanceSegmentation', 'InstanceSegmentation')], max_length=255),
        ),
    ]
